pipeline:
  identifier: Build_Cager2808_Salesforce_demo_1704258205911
  name: Build Salesforce-demo
  orgIdentifier: default
  projectIdentifier: Salesforce__App
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698735122136
        repoName: Cager2808/Salesforce-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - stepGroup:
                  name: Pre_requisite
                  identifier: Pre_requisite
                  steps:
                    - parallel:
                        - step:
                            identifier: npminstall
                            name: npm_install_and_sfdx_cli
                            spec:
                              shell: Bash
                              command: |
                                npm install --global sfdx-cli@$2.19.8
                            timeout: ""
                            type: Run
                        - step:
                            identifier: npmtest
                            name: npm_install_sfdx_git
                            spec:
                              shell: Bash
                              command: sudo npm install sfdx-git-delta@^4.x.x -g
                            timeout: ""
                            type: Run
              - step:
                  type: Run
                  name: Git_Diff_Check
                  identifier: Git_Diff_Check
                  spec:
                    shell: Bash
                    command: |2
                       git --version
                       git clone 'https://github.com/Cager2808/Salesforce-demo'
                       ls -alrt
                      cd 'Salesforce-demo'
                      git branch
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
